name = "sandlot-sluggers"
main = "src/main.ts"
compatibility_date = "2024-05-29"

[env.production]

[[d1_databases]]
binding = "PROGRESSION_DB"
database_name = "sandlot-sluggers"
database_id = "00000000-0000-0000-0000-000000000000"
